using UnityEngine;

/// <summary>
/// The baked fit that turns a furniture pack's prefab into a catalog item at its true size.
/// </summary>
/// <remarks>
/// Sits on the root of a wrapper prefab under Assets/Prefabs/ResidenceViz/Catalog/, generated by
/// CatalogArtBinder. The wrapper's shape is:
///
///     &lt;id&gt;          root, identity rotation, localScale 1, carrying this component
///      └ Art        identity rotation, localScale = baseScale, localPosition = basePosition
///         └ &lt;pack prefab&gt;   localRotation = Euler(0, yaw, 0)
///
/// **The root must stay unscaled.** ResidenceRenderer hangs the floating name label and the pick collider
/// off it, and scaling the root would stretch the label's glyphs and re-scale the collider a second
/// time on top of the size it was already given. So the whole stretch lives on the Art child, which
/// is what <see cref="Apply"/> writes.
///
/// **Yaw sits INSIDE the scaled node, and only at quarter turns.** Unity applies localScale before
/// localRotation on the same transform, so a rotation sharing a node with a non-uniform scale would
/// stretch the wrong axes; and at any angle that is not a multiple of 90° the parent's non-uniform
/// scale shears the art outright. The binder refuses a row that asks for anything else.
///
/// **Why basePosition scales componentwise alongside baseScale.** With the Art node at identity
/// rotation holding scale S and position p, the art's own local bounds (center c, extents e) land in
/// root space at center p + S∘c and size S∘2e. The bake constraints. Bottom on the floor
/// (min.y = 0) and centered in plan (center.x = center.z = 0). Give
///
///     p = ( −S.x·c.x , S.y·(e.y − c.y) , −S.z·c.z )
///
/// which is linear in S. So multiplying S by a factor f requires exactly p ← p∘f, and a resized item
/// stays on the floor and stays centered. CatalogArtBinder's Verify asserts this directly by baking at
/// the nominal size and re-checking the bounds at a non-unit factor.
/// </remarks>
public class CatalogArtFit : MonoBehaviour
{
    [Tooltip("The child holding the pack prefab. Everything the fit writes goes here, leaving the root untouched.")]
    public Transform art;

    [Tooltip("The catalog width/height/depth this bake was fitted to, in meters.")]
    public Vector3 nominalSize;

    [Tooltip("art.localScale when the item is at nominalSize.")]
    public Vector3 baseScale = Vector3.one;

    [Tooltip("art.localPosition when the item is at nominalSize.")]
    public Vector3 basePosition;

    [Tooltip("Set to keep CatalogArtBinder from regenerating this prefab. The wrapper is otherwise a " +
             "derived artifact and a regeneration overwrites any edit made inside it.")]
    public bool handTuned;

    /// <summary>
    /// Re-fits the art to <paramref name="size"/>: the item's current real dimensions, which is
    /// <c>boxSizeMeters</c> for furniture and the catalog size for a wall mount.
    /// </summary>
    public void Apply(Vector3 size)
    {
        if (art == null) return;
        if (nominalSize.x <= 0f || nominalSize.y <= 0f || nominalSize.z <= 0f) return;

        var f = new Vector3(size.x / nominalSize.x, size.y / nominalSize.y, size.z / nominalSize.z);
        art.localScale    = Vector3.Scale(baseScale,    f);
        art.localPosition = Vector3.Scale(basePosition, f);
    }
}
